# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a33545bdca472b63d0b0b17226dc405513cb4f1ea04863a8b431f36580b60a81ef7f9a7f4bd38b4ae29c8f2abde6dfb0eaaacdb9bdf74b776e79328529175c9d

test:
  secret_key_base: 27e27d9a36fa13303aaf3c23dc0c51bd1da640ea9f71b189990189ffc05c6b75a85b8ee4c340a29781cf9dd9dfc5e4c84c5aa7a5c5d4d3556db17058615d1c8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
